### ISSUE TITLE
Dead link in template

### ISSUE THREAD

**Issue by bajorgensen** [Microsoft/dcmkit#6]
The document "Template - Database Migration Proposal for Customers.docx" has a dead link on page 4: "	Familiarize yourself with Cloud Transformation Agreement (CTA) discounts" links to http://www.microsoftlicensereview.com/?p=8091 that states "Oops! That page can’t be found"

**Comment by KirillKotlyarenko** [comment]
Thanks. Since I couldn't find an updated page about CTA, I've removed the whole paragraph.
